export const INCRE_COUNTER = 'INCREMENT_COUNTER';
export const DECRE_COUNTER = 'DECREMENT_COUNTER';
export const REDIRECT = 'REDIRECT';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS';
